### ISSUE TITLE
Text mining examples

### ISSUE THREAD

**Issue by couteiral** [OxfordSchmidtAIFellows/paper-plumber#1]
We need two sets of tests to verify that PaperPlumber works. These tests should comprise at least three articles, each of them containing at least one value of some property (coherence times or error gates for quantum computing, protein stability or solubility for synthetic biology, etc). Ideally, at least one of these articles will contain more than one value.

We want to set up these articles to be our global integration test for paper-plumber: once the bare bones of the project are set up, the code should be able to extract the values from the papers autonomously.

**Comment by ShuxiangCao** [comment]
Implemented in #7.
